/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container': '#171f33',
        secondary: '#4edea3',
        'primary-fixed-dim': '#89ceff',
        'surface-container-low': '#131b2e',
        'inverse-on-surface': '#283044',
        'on-secondary-container': '#00311f',
        'surface-container-highest': '#2d3449',
        'on-surface': '#dae2fd',
        'on-error': '#690005',
        'surface-bright': '#31394d',
        'secondary-fixed': '#6ffbbe',
        'on-tertiary-fixed-variant': '#653e00',
        'tertiary-container': '#d88a00',
        'primary-container': '#0ea5e9',
        'surface-container-lowest': '#060e20',
        'inverse-surface': '#dae2fd',
        'surface-dim': '#0b1326',
        'secondary-fixed-dim': '#4edea3',
        'on-surface-variant': '#bec8d2',
        'secondary-container': '#00a572',
        'on-background': '#dae2fd',
        'on-secondary-fixed-variant': '#005236',
        'on-secondary-fixed': '#002113',
        tertiary: '#ffb95f',
        'surface-tint': '#89ceff',
        'tertiary-fixed-dim': '#ffb95f',
        'on-secondary': '#003824',
        'surface-variant': '#2d3449',
        'primary-fixed': '#c9e6ff',
        'surface-container-high': '#222a3d',
        outline: '#88929b',
        surface: '#0b1326',
        'inverse-primary': '#006591',
        primary: '#89ceff',
        error: '#ffb4ab',
        'on-primary-fixed-variant': '#004c6e',
        'on-primary-container': '#003751',
        background: '#0b1326',
        'on-primary-fixed': '#001e2f',
        'on-primary': '#00344d',
        'outline-variant': '#3e4850',
        'on-tertiary-container': '#4a2c00',
        'on-tertiary': '#472a00',
        'error-container': '#93000a',
        'tertiary-fixed': '#ffddb8',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed': '#2a1700',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xl: '48px',
        gutter: '24px',
        md: '20px',
        base: '4px',
        lg: '32px',
        sm: '12px',
        xs: '8px',
        'container-max': '1440px',
      },
      fontFamily: {
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'data-mono': ['JetBrains Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-xl': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'data-mono': ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};